### ISSUE TITLE
Current working directory is not a Cordova-based project

### ISSUE THREAD

**Issue by cissecedric** [chsakell/ionic2-angular2-firebase#2]
Hello,
I get this error while running :
ionic plugin add com-sarriaroman-photoviewer
Do you have any idea?
(I already did npm uninstall -g ionic and npm install -g ionic)
Thanks!

**Comment by chsakell** [comment]
@cissecedric create a _**www**_ folder at the root of app and try again.
Here's the [fix](https://github.com/chsakell/ionic2-angular2-firebase/commit/1f0f3d0013c695c3c51e2456177629eb03535b94).

**Comment by cissecedric** [comment]
it works now, thank you!
